// Curated Master Seed Dataset across all 5 core categories
// Guaranteed rich data for: Computer Science, AI & Data, System Design, Fiction & Sci-Fi, Habits & Psychology

export const DEFAULT_PRELOADED_BOOKS = [
  // ==========================================
  // 💻 COMPUTER SCIENCE & PROGRAMMING
  // ==========================================
  {
    id: "cs-1",
    title: "Clean Code: A Handbook of Agile Software Craftsmanship",
    subtitle: "A Handbook of Agile Software Craftsmanship",
    authors: ["Robert C. Martin"],
    publisher: "Prentice Hall",
    publishedDate: "2008",
    description: "Even bad code can function. But if code isn't clean, it can bring a development organization to its knees. Software expert Robert C. Martin presents a revolutionary paradigm with Clean Code, teaching software craftsmanship, unit testing, refactoring, and code formatting.",
    categories: ["Computers", "Computer Science", "Programming", "Software Engineering"],
    pageCount: 464,
    averageRating: 4.8,
    ratingsCount: 4500,
    thumbnail: "https://images.unsplash.com/photo-1532012164546-f432f2e3777a?w=400&q=80",
    language: "EN",
    categoryKey: "cs"
  },
  {
    id: "cs-2",
    title: "The Pragmatic Programmer",
    subtitle: "Your Journey to Mastery",
    authors: ["David Thomas", "Andrew Hunt"],
    publisher: "Addison-Wesley",
    publishedDate: "2019",
    description: "The Pragmatic Programmer is one of those rare tech books you will refer to again and again. Topics range from personal responsibility and career development to architectural techniques for keeping your code flexible, adaptable, and easy to reuse and refactor.",
    categories: ["Computers", "Computer Science", "Programming", "Software Engineering"],
    pageCount: 352,
    averageRating: 4.9,
    ratingsCount: 3800,
    thumbnail: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=400&q=80",
    language: "EN",
    categoryKey: "cs"
  },
  {
    id: "cs-3",
    title: "Introduction to Algorithms (CLRS)",
    subtitle: "Fourth Edition",
    authors: ["Thomas H. Cormen", "Charles E. Leiserson", "Ronald L. Rivest", "Clifford Stein"],
    publisher: "MIT Press",
    publishedDate: "2022",
    description: "A comprehensive update of the leading algorithms text, with new material on matchings in bipartite graphs, online algorithms, machine learning, and dynamic programming. It covers data structures, sorting, graph theory, and computational complexity.",
    categories: ["Computers", "Computer Science", "Algorithms", "Data Structures"],
    pageCount: 1312,
    averageRating: 4.7,
    ratingsCount: 5200,
    thumbnail: "https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?w=400&q=80",
    language: "EN",
    categoryKey: "cs"
  },
  {
    id: "cs-4",
    title: "Refactoring: Improving the Design of Existing Code",
    subtitle: "Second Edition",
    authors: ["Martin Fowler"],
    publisher: "Addison-Wesley Professional",
    publishedDate: "2018",
    description: "For more than twenty years, serious programmers have relied on Martin Fowler's Refactoring to improve the structural design of existing code without changing its external behavior. Covers code smells, test-driven development, and clean refactoring principles.",
    categories: ["Computers", "Computer Science", "Software Engineering", "Programming"],
    pageCount: 448,
    averageRating: 4.8,
    ratingsCount: 2900,
    thumbnail: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=400&q=80",
    language: "EN",
    categoryKey: "cs"
  },
  {
    id: "cs-5",
    title: "Structure and Interpretation of Computer Programs (SICP)",
    subtitle: "JavaScript Edition",
    authors: ["Harold Abelson", "Gerald Jay Sussman"],
    publisher: "MIT Press",
    publishedDate: "2022",
    description: "SICP has influenced computer science curricula for decades. It teaches the fundamental principles of abstraction, modularity, functional programming, recursion, interpreters, and metalinguistic abstraction in computational systems.",
    categories: ["Computers", "Computer Science", "Programming", "Functional Programming"],
    pageCount: 656,
    averageRating: 4.8,
    ratingsCount: 3100,
    thumbnail: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=400&q=80",
    language: "EN",
    categoryKey: "cs"
  },
  {
    id: "cs-6",
    title: "Learning React: Modern Patterns for Developing React Apps",
    subtitle: "Second Edition",
    authors: ["Alex Banks", "Eve Porcello"],
    publisher: "O'Reilly Media",
    publishedDate: "2020",
    description: "If you want to learn how to build efficient React applications, this practical guide puts you on the right path. Learn React components, hooks, state management, asynchronous REST API data fetching, and modern client-side architectures.",
    categories: ["Computers", "Computer Science", "React.js", "Web Development"],
    pageCount: 310,
    averageRating: 4.7,
    ratingsCount: 2100,
    thumbnail: "https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=400&q=80",
    language: "EN",
    categoryKey: "cs"
  },

  // ==========================================
  // 🧠 AI & DATA SCIENCE
  // ==========================================
  {
    id: "ai-1",
    title: "Artificial Intelligence: A Modern Approach",
    subtitle: "Fourth Edition",
    authors: ["Stuart Russell", "Peter Norvig"],
    publisher: "Pearson",
    publishedDate: "2020",
    description: "The authoritative, most widely-used introduction to the theory and practice of artificial intelligence. Explores search algorithms, knowledge representation, probabilistic reasoning, machine learning, deep neural networks, and reinforcement learning.",
    categories: ["Computers", "Artificial Intelligence", "Machine Learning", "Data Science"],
    pageCount: 1152,
    averageRating: 4.8,
    ratingsCount: 6400,
    thumbnail: "https://images.unsplash.com/photo-1677442136019-21780efad99a?w=400&q=80",
    language: "EN",
    categoryKey: "ai"
  },
  {
    id: "ai-2",
    title: "Hands-On Machine Learning with Scikit-Learn, Keras, and TensorFlow",
    subtitle: "Concepts, Tools, and Techniques to Build Intelligent Systems",
    authors: ["Aurélien Géron"],
    publisher: "O'Reilly Media",
    publishedDate: "2022",
    description: "Through a series of recent breakthroughs, deep learning has boosted the entire field of machine learning. Using concrete examples, minimal theory, and production-ready Python frameworks—Scikit-Learn, Keras, and TensorFlow—Aurélien Géron helps you build neural networks, transformers, and computer vision models.",
    categories: ["Computers", "Artificial Intelligence", "Machine Learning", "Python"],
    pageCount: 856,
    averageRating: 4.9,
    ratingsCount: 7200,
    thumbnail: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=400&q=80",
    language: "EN",
    categoryKey: "ai"
  },
  {
    id: "ai-3",
    title: "Deep Learning",
    subtitle: "Adaptive Computation and Machine Learning Series",
    authors: ["Ian Goodfellow", "Yoshua Bengio", "Aaron Courville"],
    publisher: "MIT Press",
    publishedDate: "2016",
    description: "An introduction to a broad range of topics in deep learning, covering mathematical and conceptual background, deep feedforward networks, regularization, convolutional networks, sequence modeling, and generative adversarial networks (GANs).",
    categories: ["Computers", "Artificial Intelligence", "Deep Learning", "Data Science"],
    pageCount: 800,
    averageRating: 4.7,
    ratingsCount: 4800,
    thumbnail: "https://images.unsplash.com/photo-1507413245164-6160d8298b31?w=400&q=80",
    language: "EN",
    categoryKey: "ai"
  },
  {
    id: "ai-4",
    title: "Python for Data Analysis",
    subtitle: "Data Wrangling with Pandas, NumPy, and Jupyter",
    authors: ["Wes McKinney"],
    publisher: "O'Reilly Media",
    publishedDate: "2022",
    description: "Written by the creator of the Python pandas project, this book is a practical, modern introduction to data science tools in Python. Learn to manipulate, process, clean, and crunch datasets using NumPy, pandas, matplotlib, and Jupyter notebooks.",
    categories: ["Computers", "Data Science", "Python", "Artificial Intelligence"],
    pageCount: 578,
    averageRating: 4.8,
    ratingsCount: 3900,
    thumbnail: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=400&q=80",
    language: "EN",
    categoryKey: "ai"
  },
  {
    id: "ai-5",
    title: "Life 3.0: Being Human in the Age of Artificial Intelligence",
    subtitle: "Being Human in the Age of Artificial Intelligence",
    authors: ["Max Tegmark"],
    publisher: "Knopf",
    publishedDate: "2017",
    description: "MIT professor Max Tegmark explores the future of Artificial Intelligence and what it will mean for humanity, consciousness, employment, warfare, and our existence. A profound exploration of superintelligence and the ethics of autonomous systems.",
    categories: ["Nonfiction", "Artificial Intelligence", "Technology", "Philosophy"],
    pageCount: 384,
    averageRating: 4.6,
    ratingsCount: 5100,
    thumbnail: "https://images.unsplash.com/photo-1620712943543-bcc4688e7485?w=400&q=80",
    language: "EN",
    categoryKey: "ai"
  },

  // ==========================================
  // ⚡ SYSTEM DESIGN & ARCHITECTURE
  // ==========================================
  {
    id: "sys-1",
    title: "Designing Data-Intensive Applications",
    subtitle: "The Big Ideas Behind Reliable, Scalable, and Maintainable Systems",
    authors: ["Martin Kleppmann"],
    publisher: "O'Reilly Media",
    publishedDate: "2017",
    description: "Data is at the center of many challenges in system design today. Martin Kleppmann provides an indispensable deep dive into distributed systems, replication, partitioning, transactions, consensus algorithms, batch processing, and event-driven architectures.",
    categories: ["Computers", "System Design", "Distributed Systems", "Software Architecture"],
    pageCount: 616,
    averageRating: 4.9,
    ratingsCount: 8900,
    thumbnail: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=400&q=80",
    language: "EN",
    categoryKey: "sys"
  },
  {
    id: "sys-2",
    title: "System Design Interview: An Insider's Guide",
    subtitle: "Volume 1",
    authors: ["Alex Xu"],
    publisher: "Independently published",
    publishedDate: "2020",
    description: "The definitive guide to passing technical system design interviews. Step-by-step architectural blueprints for designing rate limiters, URL shorteners, web crawlers, notification systems, news feed systems, chat systems, and cloud storage at scale.",
    categories: ["Computers", "System Design", "Software Architecture", "Scalability"],
    pageCount: 322,
    averageRating: 4.8,
    ratingsCount: 7600,
    thumbnail: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=400&q=80",
    language: "EN",
    categoryKey: "sys"
  },
  {
    id: "sys-3",
    title: "Building Microservices: Designing Fine-Grained Systems",
    subtitle: "Second Edition",
    authors: ["Sam Newman"],
    publisher: "O'Reilly Media",
    publishedDate: "2021",
    description: "Whether you are migrating from a monolithic architecture or designing from scratch, this comprehensive guide explains how to design, build, test, and deploy resilient microservices. Covers service communication, security, resiliency, and monitoring.",
    categories: ["Computers", "System Design", "Microservices", "Software Architecture"],
    pageCount: 612,
    averageRating: 4.7,
    ratingsCount: 3300,
    thumbnail: "https://images.unsplash.com/photo-1544197150-b99a580bb7a8?w=400&q=80",
    language: "EN",
    categoryKey: "sys"
  },
  {
    id: "sys-4",
    title: "Clean Architecture: A Craftsman's Guide to Software Structure",
    subtitle: "A Craftsman's Guide to Software Structure and Design",
    authors: ["Robert C. Martin"],
    publisher: "Prentice Hall",
    publishedDate: "2017",
    description: "Practical software architecture rules for software designers. Robert C. Martin explains component principles, boundary enforcement, decoupling business rules from frameworks and databases, and designing systems that stand the test of time.",
    categories: ["Computers", "System Design", "Software Architecture", "Programming"],
    pageCount: 432,
    averageRating: 4.7,
    ratingsCount: 4100,
    thumbnail: "https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?w=400&q=80",
    language: "EN",
    categoryKey: "sys"
  },
  {
    id: "sys-5",
    title: "Site Reliability Engineering (SRE)",
    subtitle: "How Google Runs Production Systems",
    authors: ["Betsy Beyer", "Chris Jones", "Jennifer Petoff", "Niall Richard Murphy"],
    publisher: "O'Reilly Media",
    publishedDate: "2016",
    description: "Members of Google's Site Reliability Engineering team explain how their organization builds, deploys, monitors, and maintains the largest, highest-availability software systems in the world. Essential reading for distributed systems engineers.",
    categories: ["Computers", "System Design", "DevOps", "Infrastructure"],
    pageCount: 550,
    averageRating: 4.8,
    ratingsCount: 4900,
    thumbnail: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=400&q=80",
    language: "EN",
    categoryKey: "sys"
  },

  // ==========================================
  // 📖 FICTION & SCI-FI
  // ==========================================
  {
    id: "fic-1",
    title: "Dune",
    subtitle: "The Epic Masterpiece",
    authors: ["Frank Herbert"],
    publisher: "Chilton Books",
    publishedDate: "1965",
    description: "Set on the desert planet Arrakis, Dune tells the story of Paul Atreides, heir to a noble family tasked with ruling an inhospitable world where the only thing of value is the 'spice' melange. An iconic science fiction epic exploring politics, ecology, and human potential.",
    categories: ["Fiction", "Science Fiction", "Space Opera", "Classics"],
    pageCount: 688,
    averageRating: 4.8,
    ratingsCount: 15000,
    thumbnail: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=400&q=80",
    language: "EN",
    categoryKey: "fic"
  },
  {
    id: "fic-2",
    title: "Foundation",
    subtitle: "The Foundation Series",
    authors: ["Isaac Asimov"],
    publisher: "Gnome Press",
    publishedDate: "1951",
    description: "For twelve thousand years the Galactic Empire has ruled supreme. Now it is dying. Only Hari Seldon, creator of the science of psychohistory, can see into the future—to an age of darkness—and sets out to preserve civilization through the Foundation.",
    categories: ["Fiction", "Science Fiction", "Space Opera"],
    pageCount: 255,
    averageRating: 4.7,
    ratingsCount: 11000,
    thumbnail: "https://images.unsplash.com/photo-1506466010722-395aa2bef877?w=400&q=80",
    language: "EN",
    categoryKey: "fic"
  },
  {
    id: "fic-3",
    title: "The Three-Body Problem",
    subtitle: "Remembrance of Earth's Past",
    authors: ["Cixin Liu", "Ken Liu"],
    publisher: "Tor Books",
    publishedDate: "2014",
    description: "Set against the backdrop of China's Cultural Revolution, a secret military project sends signals into space to establish contact with aliens. An alien civilization on the brink of destruction captures the signal and plans to invade Earth. Hugo Award Winner.",
    categories: ["Fiction", "Science Fiction", "Hard Sci-Fi"],
    pageCount: 400,
    averageRating: 4.7,
    ratingsCount: 9800,
    thumbnail: "https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?w=400&q=80",
    language: "EN",
    categoryKey: "fic"
  },
  {
    id: "fic-4",
    title: "Project Hail Mary",
    subtitle: "A Novel",
    authors: ["Andy Weir"],
    publisher: "Ballantine Books",
    publishedDate: "2021",
    description: "Ryland Grace is the sole survivor on a desperate, last-chance mission—and if he fails, humanity and the earth itself will perish. Except right now, he doesn't know that. He can't even remember his own name. A gripping scientific survival adventure.",
    categories: ["Fiction", "Science Fiction", "Space Adventure"],
    pageCount: 496,
    averageRating: 4.9,
    ratingsCount: 16500,
    thumbnail: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=400&q=80",
    language: "EN",
    categoryKey: "fic"
  },
  {
    id: "fic-5",
    title: "1984",
    subtitle: "A Dystopian Masterpiece",
    authors: ["George Orwell"],
    publisher: "Secker & Warburg",
    publishedDate: "1949",
    description: "Winston Smith toils in the Ministry of Truth, rewriting the past to suit the Party. Yet he longs for truth and rebellion against Big Brother. A terrifying vision of totalitarian control, censorship, doublethink, and surveillance.",
    categories: ["Fiction", "Classics", "Dystopian", "Literature"],
    pageCount: 328,
    averageRating: 4.8,
    ratingsCount: 22000,
    thumbnail: "https://images.unsplash.com/photo-1543002588-bfa74002ed7e?w=400&q=80",
    language: "EN",
    categoryKey: "fic"
  },
  {
    id: "fic-6",
    title: "To Kill a Mockingbird",
    subtitle: "A Classic of Modern American Literature",
    authors: ["Harper Lee"],
    publisher: "J. B. Lippincott & Co.",
    publishedDate: "1960",
    description: "The unforgettable novel of a childhood in a sleepy Southern town and the crisis of conscience that rocked it. Compassionate, dramatic, and deeply moving, taking readers to the roots of human empathy, justice, kindness, and cruelty.",
    categories: ["Fiction", "Classics", "Literature"],
    pageCount: 281,
    averageRating: 4.8,
    ratingsCount: 18000,
    thumbnail: "https://images.unsplash.com/photo-1495640388908-05fa85288e61?w=400&q=80",
    language: "EN",
    categoryKey: "fic"
  },

  // ==========================================
  // 📈 HABITS & PSYCHOLOGY & SELF-HELP
  // ==========================================
  {
    id: "psy-1",
    title: "Atomic Habits: An Easy & Proven Way to Build Good Habits",
    subtitle: "Tiny Changes, Remarkable Results",
    authors: ["James Clear"],
    publisher: "Avery",
    publishedDate: "2018",
    description: "No matter your goals, Atomic Habits offers a proven framework for improving every day. James Clear reveals practical strategies to form good habits, break bad ones, master tiny daily behaviors, and achieve remarkable long-term compound growth.",
    categories: ["Self-Help", "Psychology", "Habits", "Personal Development"],
    pageCount: 320,
    averageRating: 4.9,
    ratingsCount: 25000,
    thumbnail: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=400&q=80",
    language: "EN",
    categoryKey: "psy"
  },
  {
    id: "psy-2",
    title: "Thinking, Fast and Slow",
    subtitle: "The International Bestseller",
    authors: ["Daniel Kahneman"],
    publisher: "Farrar, Straus and Giroux",
    publishedDate: "2011",
    description: "Nobel laureate Daniel Kahneman takes us on a groundbreaking tour of the mind and explains the two systems that drive the way we think: System 1 (fast, intuitive, emotional) and System 2 (slower, deliberative, logical). Explores cognitive biases and decision making.",
    categories: ["Psychology", "Behavioral Economics", "Nonfiction", "Self-Help"],
    pageCount: 499,
    averageRating: 4.7,
    ratingsCount: 14000,
    thumbnail: "https://images.unsplash.com/photo-1499750310107-5fef28a66643?w=400&q=80",
    language: "EN",
    categoryKey: "psy"
  },
  {
    id: "psy-3",
    title: "Deep Work: Rules for Focused Success in a Distracted World",
    subtitle: "Rules for Focused Success in a Distracted World",
    authors: ["Cal Newport"],
    publisher: "Grand Central Publishing",
    publishedDate: "2016",
    description: "Deep work is the ability to focus without distraction on cognitively demanding tasks. Cal Newport demonstrates that in an economy flooded with shallow distractions, cultivating deep work allows you to master complex skills and achieve peak productivity.",
    categories: ["Self-Help", "Productivity", "Psychology", "Personal Growth"],
    pageCount: 296,
    averageRating: 4.8,
    ratingsCount: 9400,
    thumbnail: "https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=400&q=80",
    language: "EN",
    categoryKey: "psy"
  },
  {
    id: "psy-4",
    title: "The Psychology of Money: Timeless Lessons on Wealth, Greed, and Happiness",
    subtitle: "Timeless Lessons on Wealth, Greed, and Happiness",
    authors: ["Morgan Housel"],
    publisher: "Harriman House",
    publishedDate: "2020",
    description: "Doing well with money isn't necessarily about what you know. It's about how you behave. And behavior is hard to teach, even to really smart people. Morgan Housel shares 19 short stories exploring the strange ways people think about money, risk, ego, and happiness.",
    categories: ["Psychology", "Personal Finance", "Self-Help", "Mindset"],
    pageCount: 256,
    averageRating: 4.9,
    ratingsCount: 18000,
    thumbnail: "https://images.unsplash.com/photo-1553729459-efe14ef6055d?w=400&q=80",
    language: "EN",
    categoryKey: "psy"
  },
  {
    id: "psy-5",
    title: "The Power of Habit: Why We Do What We Do in Life and Business",
    subtitle: "Why We Do What We Do in Life and Business",
    authors: ["Charles Duhigg"],
    publisher: "Random House",
    publishedDate: "2012",
    description: "Award-winning business reporter Charles Duhigg takes us to the thrilling edge of scientific discoveries that explain why habits exist and how they can be changed. Decodes the Habit Loop: Cue, Routine, and Reward.",
    categories: ["Psychology", "Habits", "Self-Help", "Behavioral Science"],
    pageCount: 371,
    averageRating: 4.7,
    ratingsCount: 13000,
    thumbnail: "https://images.unsplash.com/photo-1506784983877-45594efa4cbe?w=400&q=80",
    language: "EN",
    categoryKey: "psy"
  },
  {
    id: "psy-6",
    title: "Mindset: The New Psychology of Success",
    subtitle: "How We Can Learn to Fulfill Our Potential",
    authors: ["Carol S. Dweck"],
    publisher: "Ballantine Books",
    publishedDate: "2006",
    description: "World-renowned Stanford psychologist Carol S. Dweck discovers a simple but groundbreaking idea: the power of mindset. Explains how a growth mindset fosters motivation, resilience, learning, and extraordinary accomplishment compared to a fixed mindset.",
    categories: ["Psychology", "Self-Help", "Personal Growth", "Education"],
    pageCount: 320,
    averageRating: 4.7,
    ratingsCount: 8800,
    thumbnail: "https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?w=400&q=80",
    language: "EN",
    categoryKey: "psy"
  }
];
